name: Node.js Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installs dependencies and caches them
        run: npm ci
      - name: Runs our static analysis tool, ESLint
        run: npm run lint
      - name: Runs our tests
        run: npm run test
      - name: Builds our application
        run: npm run build --if-present
